
services:

  db_micro:
    image: postgres:15-alpine
    container_name: db_pstg_container
    restart: always
    volumes:
      - db_data_sy:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRESS_PORT}:5432"
    networks:
      - wpsite
  db_word:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpsite
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - wpsite
    depends_on:
      - db_micro 
  phpmyadmin:
    depends_on:
      - db_word
    image: phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db_word
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wpsite
  wordpress:
    depends_on:
      - db_word
    image: wordpress:fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_word:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8082');
        define('WP_SITEURL', 'http://localhost:8082');
    volumes:
      - ./wordpress:/var/www/html/wordpress  # Changed from /var/www/html 
    networks:
      - wpsite
  app:
    build:
      context: ./symfony
    container_name: symfony_app
    volumes:
      - ./symfony:/var/www/html/symfony  
    restart: always
    depends_on:
      - db_micro
      - wordpress
    networks:
      - wpsite
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_pstg_container:5432/${POSTGRES_DB}"
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      WORDPRESS_API_URL : nginx:82

  nginx:
    image: nginx:alpine
    depends_on:
      - app
      - wordpress
    ports:
      - "8082:82"  
      - "8081:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./symfony:/var/www/html/symfony  
      - ./wordpress:/var/www/html/wordpress

    networks:
      - wpsite

networks:
  wpsite:
    driver: bridge  

volumes:
  db_data:
  db_data_sy:
